### ISSUE TITLE
Any pretrained models available?

### ISSUE THREAD

**Issue by AndroYD84** [Andrea-V/MusAE#2]
Hello, would it be possible to share your pretrained model? I'm very curious to test this, thank you very much for sharing your work.

**Comment by Andrea-V** [comment]
Hi AndroYD84, sorry for the late response.
You can find some pretrained models at this link:
https://drive.google.com/open?id=1fr16B2MGVAtyk3W4D3SgI2Z983lKCE2U

The files named GMMusAE are the gaussian mixture models (16bar sequences), the others are single gaussian MusAE on 2bar sequences.
