### ISSUE TITLE
Any conditional-generation method available??

### ISSUE THREAD

**Issue by NullXeronier** [Andrea-V/MusAE#3]
Hello, would it be possible to share your conditional-generation code
``` test_x = preprocess(user_input_midi),  model.predict(test_x) ``` ??
I'm very curious to test this too, 
Thank you very much for sharing your work.

**Comment by Andrea-V** [comment]
Hello ikarus, sorry for the late response.
unfortunately, I don't have any code available for conditional generating code, but you can do it by encoding an arbitrary MIDI sequence and then generating the latent codes that stems for that.
