### ISSUE TITLE
Unknown Function : decoders.py : LowDecoder layer...

### ISSUE THREAD

**Issue by NullXeronier** [Andrea-V/MusAE#4]
I wonder LowDecoder Layer is not in Keras layers
( ref https://github.com/Andrea-V/MusAE/blob/master/decoders.py#L120 )

How Can I Implement that function in keras ?

Thanks

**Comment by Andrea-V** [comment]
Hi Ikarus,
that part of code should not be there actually, LowDecoder was part of an experimental hierarchical version of the model that I never managed to make it work. So you can safely delete that function and nothing should change.

I you want to implement the LowDecoder, it was meant to be a clone of the simple decoder model that took in input a "partial latent code" (responsible for encoding only a part of the music sequence) and returned the corresponding part of the sequence. In practice it should be a CuDNNLSTM just as the high_decoder, just with different input and outputs.
